import { CardProps } from "../types/page";
import KJ from "@/assets/images/KJ.png";
import KJBG from "@/assets/images/KJBackground.png";
import IT from "@/assets/images/IT.png";
import ITBG from "@/assets/images/ITBackground.png";
import BW from "@/assets/images/BW.png";
import BWBG from "@/assets/images/BWBackground.png";
import FLR from "@/assets/images/ER.png";
import FLRBG from "@/assets/images/ERBG.png";

export const cards: CardProps[] = [
  {
    id: 1,
    title: "Mount Kilimanjaro",
    distance: "60 mi / 97 km",
    virtualPostcards: 5,
    hasStreetView: false,
    image: KJ,
    background: KJBG,
    price: 3,
  },
  {
    id: 2,
    title: "Inca Trail",
    distance: "26 mi / 42 km",
    virtualPostcards: 4,
    hasStreetView: true,
    image: IT,
    background: ITBG,
    price: 4,
  },
  {
    id: 3,
    title: "Berlin Wall",
    distance: "30 mi / 48 km",
    virtualPostcards: 5,
    hasStreetView: true,
    image: BW,
    background: BWBG,
    price: 5,
  },
  {
    id: 4,
    title: "Flower Route",
    distance: "41 mi / 66 km",
    virtualPostcards: 4,
    hasStreetView: true,
    image: FLR,
    background: FLRBG,
    price: 6,
  },
  {
    id: 5,
    title: "Mount Kilimanjaro",
    distance: "60 mi / 97 km",
    virtualPostcards: 5,
    hasStreetView: false,
    image: KJ,
    background: KJBG,
    price: 7,
  },
  {
    id: 6,
    title: "Inca Trail",
    distance: "26 mi / 42 km",
    virtualPostcards: 4,
    hasStreetView: true,
    image: IT,
    background: ITBG,
    price: 8,
  },
  {
    id: 7,
    title: "Berlin Wall",
    distance: "30 mi / 48 km",
    virtualPostcards: 5,
    hasStreetView: true,
    image: BW,
    background: BWBG,
    price: 9,
  },
  {
    id: 8,
    title: "Flower Route",
    distance: "41 mi / 66 km",
    virtualPostcards: 4,
    hasStreetView: true,
    image: FLR,
    background: FLRBG,
    price: 10,
  },
  {
    id: 9,
    title: "Mount Kilimanjaro",
    distance: "60 mi / 97 km",
    virtualPostcards: 5,
    hasStreetView: false,
    image: KJ,
    background: KJBG,
    price: 11,
  },
  {
    id: 10,
    title: "Inca Trail",
    distance: "26 mi / 42 km",
    virtualPostcards: 4,
    hasStreetView: true,
    image: IT,
    background: ITBG,
    price: 12,
  },
  {
    id: 11,
    title: "Berlin Wall",
    distance: "30 mi / 48 km",
    virtualPostcards: 5,
    hasStreetView: true,
    image: BW,
    background: BWBG,
    price: 13,
  },
  {
    id: 12,
    title: "Flower Route",
    distance: "41 mi / 66 km",
    virtualPostcards: 4,
    hasStreetView: true,
    image: FLR,
    background: FLRBG,
    price: 14,
  },
  {
    id: 13,
    title: "Mount Kilimanjaro",
    distance: "60 mi / 97 km",
    virtualPostcards: 5,
    hasStreetView: false,
    image: KJ,
    background: KJBG,
    price: 15,
  },
  {
    id: 14,
    title: "Inca Trail",
    distance: "26 mi / 42 km",
    virtualPostcards: 4,
    hasStreetView: true,
    image: IT,
    background: ITBG,
    price: 16,
  },
  {
    id: 15,
    title: "Berlin Wall",
    distance: "30 mi / 48 km",
    virtualPostcards: 5,
    hasStreetView: true,
    image: BW,
    background: BWBG,
    price: 17,
  },
  {
    id: 16,
    title: "Flower Route",
    distance: "41 mi / 66 km",
    virtualPostcards: 4,
    hasStreetView: true,
    image: FLR,
    background: FLRBG,
    price: 18,
  },
  {
    id: 17,
    title: "Mount Kilimanjaro",
    distance: "60 mi / 97 km",
    virtualPostcards: 5,
    hasStreetView: false,
    image: KJ,
    background: KJBG,
    price: 19,
  },
  {
    id: 18,
    title: "Inca Trail",
    distance: "26 mi / 42 km",
    virtualPostcards: 4,
    hasStreetView: true,
    image: IT,
    background: ITBG,
    price: 20,
  },
  {
    id: 19,
    title: "Berlin Wall",
    distance: "30 mi / 48 km",
    virtualPostcards: 5,
    hasStreetView: true,
    image: BW,
    background: BWBG,
    price: 21,
  },
  {
    id: 20,
    title: "Flower Route",
    distance: "41 mi / 66 km",
    virtualPostcards: 4,
    hasStreetView: true,
    image: FLR,
    background: FLRBG,
    price: 22,
  },
];
